### ISSUE TITLE
Issue with 2 trees, one of them loaded with state plugin

### ISSUE THREAD

**Issue by johaven** [arvindr21/jsTree-directive#19]
If multiple trees are loaded and one of them will have the state parameter.
Errors between the trees occur when traverses the same folders.

TypeError: a.state is undefined
...d:function(a){return a=this.get_node(a),a&&a.state.loaded},is_loading:function(a...

or

TypeError: this._model.data[b].state is undefined
...model.data.hasOwnProperty(b)&&"#"!==b&&(this._model.data[b].state.opened&&a.core...

**Comment by arvindr21** [comment]
Can you please share a fiddle with the issue?

**Comment by yoyoprs** [comment]
Finally, It's happen when in my state storage i have 2 path open in a same root folder.

See video: http://we.tl/ar6Qxbih29

**Comment by yoyoprs** [comment]
This is confirmed by the developer of jstree, it comes right jstree Directive.
It has nothing to do with the state plugin
With the last version of Jstree in master branch, i got this error:

TypeError: f.id.replace is not a function
...str(1).replace(a.jstree.idregex,"\\$&"):f.id.replace(a.jstree.idregex,"\\$&"))):...

How to reproduce:
- open two subchilds that have the same parent.
- launch a refresh ($('#tree').jstree(true).refresh())

**Comment by arvindr21** [comment]
Oh! ok. Any proposed fix for this issue?

**Comment by yoyoprs** [comment]
Not yet had time to dissect the code, but it should be easy for you I think?

**Comment by arvindr21** [comment]
As of now, I do not have a solution for this. May be you could save last opened children nodes in local storage and open the tree nodes till this level recursively? I don't know, may not be the correct way to do it.

Do let me know if you find a fix for this. Thanks!
