### ISSUE TITLE
How to search with input-text into jsTree directive. 

### ISSUE THREAD

**Issue by Annecv33** [arvindr21/jsTree-directive#20]
Hi, this could help you if you want to search using an input-text with Arvind's directive: http://jstree-directive.herokuapp.com/#/plugins

I used the Arvind's jsTree-directive example and I changed the tree-plugins attribute, putting equals to search and it works perfectly! :

<div class="col-md-4 tree-browser">
	  <js-tree 	tree-plugins="search"
      	tree-events="select_node:nodeSelected" 
      	tree-ajax="/api/tree" 
      	tree-core="tree_core"
      ></js-tree>
    </div>

Thanks Arvind!

**Comment by arvindr21** [comment]
:+1:
