### ISSUE TITLE
custom context menu doesnt work 

### ISSUE THREAD

**Issue by antonyboom** [arvindr21/jsTree-directive#34]
so this example of my [plunker](https://plnkr.co/edit/LyF3DAosCTpBb7SMSpsQ?p=preview). I did every step follow by doc but the custom menu doesn't work. Where is my problem?

**Comment by antonyboom** [comment]
The problem was that directive has provided here isn't working. I have found some fiddle example with old one directive and put it in my app, hope it helps

**Comment by Farhan42** [comment]
To use custom context menu, replace code in the directive with the provided one
**Orignal:**
if (config.plugins.indexOf('contextmenu') >= 0) {
                    if (a.treeContextmenu) {
                        config.contextmenu = s[a.treeContextmenu];
                    }
                }

**Replace With**
if (config.plugins.indexOf('contextmenu') >= 0) {
                    if (a.treeContextmenu) {
                        config.contextmenu = s[a.treeContextmenu];
                        config.contextmenu = { items: s[a.treeContextmenu] };
                    }
                }
