### ISSUE TITLE
Search plugin results double input field

### ISSUE THREAD

**Issue by purevdondov** [arvindr21/jsTree-directive#8]
I used it like below:
&lt;js-tree tree-plugins="search,wholerow" tree-data="scope" tree-events="select_node:nodeSelected" tree-model="tree"&gt;

Screen shot:
![untitled](https://cloud.githubusercontent.com/assets/6018808/5427553/4b4ba8f6-83dd-11e4-8ec0-6a492678be4c.jpg)

**Comment by arvindr21** [comment]
Fixed. Refer : http://jsfiddle.net/arvindravulavaru/duz96so7/2/

**Comment by purevdondov** [comment]
Thanks, it works now. Closing the issue.
