### ISSUE TITLE
Same name nodes in parent folder disappear.

### ISSUE THREAD

**Issue by JackZhang1988** [arvindr21/jsTree-directive#9]
I use this directive show my folder files.  My tree view like below.
![qq 20141223115119](https://cloud.githubusercontent.com/assets/1697710/5534398/54d98c4e-8a9a-11e4-8690-65e4e68dcc01.jpg)

In folder 1231, there are some files which name same with some files in parent folder. But when i open this sub folder, the same name nodes in parent folder disappear. 
![qq 20141223115442](https://cloud.githubusercontent.com/assets/1697710/5534407/cd4bd66e-8a9a-11e4-8125-82ee7e6160f8.jpg)

How to fix this problem?

**Comment by arvindr21** [comment]
<< no update >>
